version: '3'

services:
  notion-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: notion-proxy
    container_name: notion-proxy
    restart: unless-stopped
    #env_file: .env
    ports:
      - "127.0.0.1:3333:3333"
    volumes:
      - ./config:/notion-proxy/config
      - ./cache:/notion-proxy/cache

